name: Go
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  go:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go get ./cmd/...

      - name: Build
        run: go build -ldflags="-s -w" ./cmd/...

      - name: Test
        run: go test ./...
