name: Linter
on:
  pull_request:

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
